# Generated by Django 4.1.2 on 2022-10-06 20:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='note',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='schedule_type',
            field=models.IntegerField(choices=[(0, 'Полный'), (1, 'н/н'), (2, 'ч/н')], default=0),
        ),
    ]
