# Generated by Django 4.1.2 on 2022-10-06 20:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_lesson_note_alter_lesson_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
