# Generated by Django 4.1.2 on 2022-10-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_lesson_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
